### PR TITLE
[SP-2974][BACKLOG-10830] update the Angular dependency in the Marketp…

### PR DESCRIPTION
**Pull request by mchen-len-son**
…lace plugin

 - Upgrade client side dependencies
 - Change client side bundle descriptor to package.json
 - Fixes due to angular upgrade
 - Fixes due to angular-bootstrap upgrade
 - Delete unused feature files
 - Include fonts referred by globalCrystal.css
 - Clean-up dependencies and fix server entry point
 - Fix client entry point
 - Upgrade angular-translate due to async issues
 - upgraded angular version to 1.5.8

This is a backport of #114

### CODE REVIEW

**Comment by nantunes** [comment]
Shouldn't  42f4916f095d93f8dcd36e501fb9e2db89331274 and a12f29ab61860201067cc910020489e9e97349bf also be included? They resolve regressions introduced by this cherry-picked commit. @pamval

**Comment by nantunes** [comment]
The f52c63eb65d8796a00d504c70e5ec7adf000bbe0 commit is also part of this batch of changes. @pamval

**Comment by nantunes** [comment]
I approved the changes despite my comments, because I don't known if backports are made _per_ PR. So ignore them if they make no sense. 👍

**Comment by mchen-len-son** [comment]
@nantunes added https://github.com/pentaho/marketplace/commit/f52c63eb65d8796a00d504c70e5ec7adf000bbe0 
and the others are not to be backported as discussed

**Pull request merged**
